name: deep_observer
description: Library for efficient handling of reactive states in Flutter.
version: 1.0.1
repository: https://github.com/carlosparra1998/deep_observer
issue_tracker: https://github.com/carlosparra1998/deep_observer/issues
topics:
  - reactivity
  - state-management
  - provider

environment:
  sdk: ^3.7.0

dependencies:
  flutter:
    sdk: flutter

  uuid: ^4.5.1

dev_dependencies:
  lints: ^5.0.0
  test: ^1.24.0
